### ISSUE TITLE
Code Review (27.28-09-2021)

### ISSUE THREAD

**Issue by PhiSyX** [lmd-dev/lmd-supergruik#1]
Hello.

Voici une revue de code sur ce qui pourrait être amélioré ou ajouté pour ce projet.

1. Ajouter la syntaxe de module ES6 (import/export) !
    Pour une meilleur auto-complétion au niveau des éditeurs de texte, tel que VSCode.
2. Utiliser le package manager (npm) pour les dépendances ?
    Notamment pour installer `pixi.js`, et toujours pour une meilleur auto-complétion, et ne pas avoir à copier les types de `pixi.js` à la main.
3. Beaucoup de définition de méthode en double comme le cas suivant dans plusieurs fichiers : 
    https://github.com/lmd-dev/lmd-supergruik/blob/68ca5d7e629cbb3b49c25dda356debda63369502/src/core/graphical-item-factory.ts#L9-L17
   Il pourrait être intéressant de se créer une interface qui contiendrait uniquement les positions `x` et `y` ; et la classe `Coordinates` implémentera cette interface. Exemple : 
  ```ts 
  export interface CoordinatesInterface 
  { 
       x: number;
       y: number;
  }

  export class Coordinates implements CoordinatesInterface 
  {
      // code
  }
  ```

  Les méthodes quant à elles n'auront besoin que de l'interface. Pour reprendre l'exemple ci-haut :

  ```ts
  import type { CoordinatesInterface } from "core/coordinates";

  createWaste(type: WasteType, coordinates: CoordinatesInterface, rotation: number, speed: number): Waste;
  createSuperGruik(coordinates: CoordinatesInterface): SuperGruik;
  ```
4. Type de retour des méthodes parfois omis, parfois pas : il faut faire un choix ! 
    Souvent pour les méthodes dont le type de retour est `void` :D 
5. `event.keyCode` déprécié 
    https://github.com/lmd-dev/lmd-supergruik/blob/68ca5d7e629cbb3b49c25dda356debda63369502/src/views/view-game.ts#L63-L65
   Aujourd'hui on préféra utiliser `event.key` ou `event.code` au choix !

Sinon je n'ai pas grand chose à dire niveau fonctionnalité, ou performance, ça m'a l'air d'être du bon code ! 👍 

En bonus, ce projet pourrait avoir un serveur de développement (dixit serverless) facilement installable avec [Vite](https://vitejs.dev/guide/). Il est rapide, pas lourd, pas de configuration nécessaire (sauf si besoin), et ça n'installe pas de framework/lib comme vue ou react, etc., si tu n'en veux pas. Cela te permettra entre autres d'avoir un système de rechargement à chaud des modules à chaque sauvegarde des fichiers sources, fini les F5 ! (Promis je ne suis pas sponso par Vite)

![CodeReview2021-09-28-005500](https://user-images.githubusercontent.com/738010/134996101-07495d5f-697a-495f-9dd6-58914816afc4.png)

Je comprendrai, que certaines choses ne soient pas la priorité ou, le choix de ne pas corriger ou ajouter tous ces petits détails ! ( n'hésite pas à close si jamais )

Voilà voilà, à bientôt !

**Comment by lmd-dev** [comment]
Merci pour la review @PhiSyX !

Pour les points 1 et 2, j'aurais bien aimé le faire, mais ce n'est pas possible sans passé par un Webpack like. Ici le code est exécuté coté client, et il n'est pas possible pour le navigateur de trouver ces fichiers dans les /nodes_modules. Et je ne veux pas d'une usine à gaz comme WebPack pour un projet aussi simple. Par contre, s'il existe une solution plus simple, je suis preneur. Mais à ce jour, je n'ai rien trouvé qui permette de faire du NPM et du TypeScript coté client et de manière élégante. Pourtant, j'adore les modules ES6 !

Pour le 3, effectivement la solution de l'interface est intéressante. Ici, j'avoue avoir profité de l'occasion pour jouer avec les surcharges :D

Pour le 4, C++ m'a appris à ne jamais déclarer les retour void et ça me colle à la peau. A revoir donc.

Pour le 5, je prends note. A changer également.  

Enfin, je prends note pour Vite, il faut que j'aille voir cela.

Encore merci pour le temps pris et pour toutes ces informations :-)

**Comment by PhiSyX** [comment]
Totalement d'accord avec les réponses que tu as donné !

On pourrait totalement se passer de tous ces outils (bundlers et consorts) pour n'écrire que du code modulaire ES6 dans les navigateurs d'aujourd'hui, mais on y perdrait en "confort" de développement pour nous développeurs (parce que types, éditeurs, ...). Et mine de rien, c'est important le confort dans ce que l'on fait, enfin je trouve. 

Aujourd'hui si je recommande Vite, c'est justement parce qu'il fait parti de ces conforts de développement pour les développeurs JS/TScripteux. Tout comme Webpack l'est aussi en quelque sorte, mais je ne le recommande pas car bien trop compliqué à mettre en place, et puis trop "lent" (pas Vite (👍)) pour ce que l'on veut faire.
Ce que fait Vite côté serveur de développement, dans les grandes lignes, c'est qu'il va servir automatiquement toutes les dépendances `node_modules` et se chargera tout seul comme un grand de faire la conversion `import Pixi from "pixi.js"` en `import Pixi from "node_module/pixi.js"` dans le code renvoyé au client (au navigateur).
Pour la construction d'un projet, Vite va se comporter comme un bundler se basant sur le contenu des fichiers HTML (à la manière du bundler [parceljs](https://parceljs.org)).
Enfin, j'imagine que tu vois le principe de ces outils x)

Dans la capture d'écran que j'ai montré, le projet utilisait Vite : on peut y voir ce que contient le dossier `dist/` après la construction de ce projet. Simple, efficace !
